name = "manjeet"
city = "amritsar"
state = "punjab"
print(name,city,state)
#manjeet is m
name = "manjeet"
hno = 570
print(type(hno))
print(type(name))
number = 3.3
print(type(number))
salary = 30000
print(salary)
salary = 30000
bonus = 5000
total = salary + bonus
print(total)
name = input("enter your name:")
print("helo", name)
print(keyword.kwlist)
import keyword
print(keyword.kwword)
a = 7
b = 5
print(a + b)
name = "manjeet"
print("name")